### ISSUE TITLE
Feature request trust on device

### ISSUE THREAD

**Issue by guilhermecomum** [storvik/emacs-lastpass#12]
First off all thank you for create this amazing emacs package +1
The `lpass` has a feature to trust on device to not request everytime the master password, I made change locally just including `--trust` on login function and works like a charm. I believe this not should come enabled by default but it would be great to have a config to enable this feature.

**Comment by storvik** [comment]
Thank you for reporting this, great to see that someone is using this package! I personally don't use multifactor authentication so I didn't know about the `--trust` flag. A new variable `lastpass-trust-login` is added to turn this on / off. A simple `setq` can be used: 
``` elisp
(setq lastpass-trust-login t)
```
