### ISSUE TITLE
lastpass-list-all-make-element: Wrong type argument: wholenump, -10

### ISSUE THREAD

**Issue by eamonnsullivan** [storvik/emacs-lastpass#3]
I get this when logged in and try lastpass-list-all. I get this on Emacs 26 snapshot on Ubuntu 16.04 and an Emacs 25.1 on Mac OS X. Let me know what other information you need to track this down.

**Comment by eamonnsullivan** [comment]
I manage to get further in the list when I made sure each of my elements have usernames and that there aren't any query strings in the URLs. I printed out (via (message ...)) each of the elements that lastpass-list-all-make-element is processing, but I can't spot any obvious issue with the one it's choking on. 

In general, this function is really, really fragile and is likely to break on any input that doesn't look like yours. I'm probably going to just give up on it, and come back maybe when lastpass provides a proper API... You can't process raw text like that with multiple complicated regexes. It isn't going to work if the input is ever slightly out of the ordinary. 

Too bad. This is a good idea. Good luck with it.

**Comment by storvik** [comment]
Thanks for your interest in this package. I did know about this "weak spot" in my code and actually had a solution in mind. Now the parsing is rewritten and simplified. You can also change the lastpass-list-all-delimiter variable to fit your use case. This variable is currently set to comma, which means there should be no commas in your id, account name, group name or user name. I recon this wont be a problem, as these fields mostly shouldn't contain commas. 

I would appreciate if you try again and provide som feedback!
