### ISSUE TITLE
use latest auth-source plugin mechanism if possible

### ISSUE THREAD

**Issue by tzz** [storvik/emacs-lastpass#4]
Similarly to what we did for https://github.com/DamienCassou/auth-password-store/issues/24 maybe this library can use the `auth-source-backend-parser-functions` if it's available, instead of advice?

**Comment by storvik** [comment]
I actually contacted Damien Cassou in the process of implementing auth-source compatibility. He gave me this snippet which is used in `lastpass.el`: 

``` emacs-lisp
(if (boundp 'auth-source-backend-parser-functions)
    (add-hook 'auth-source-backend-parser-functions #'lastpass-auth-source-backend-parse)
  (advice-add 'auth-source-backend-parse :before-until #'lastpass-auth-source-backend-parse))
```

Is this what you're looking for?

**Comment by tzz** [comment]
@storvik exactly :) I just looked at the README, which only mentions the `advice-add`, so I didn't know you had done this. Thanks.

**Comment by storvik** [comment]
@tzz Great! I'll mention it in the README. Thank you for providing feedback :-)
